version: "3"
services:
  php:
    build: './compose/php74'
    container_name: lamp_php74
    volumes:
      - ./src/project:/var/www/html/
    depends_on:
      - mysql
    networks:
      - mynet

  mysql:
    build: './compose/mysql'
    container_name: lamp_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./src/data:/var/lib/mysql
      - ./src/sql:/root/sql/
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - mynet

  phpmyadmin:
    build: './compose/phpmyadmin'
    container_name: lamp_pma
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - mynet

  apache:
    image: httpd:2.4-alpine
    build: './compose/apache'
    container_name: lamp_apache
    depends_on:
      - php
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - ./src/project:/var/www/html/
      - ./compose/apache/:/usr/local/apache2/conf.d
networks:
  mynet: