version: "3"
services:
  php:
    image: php:7.4.11-fpm-alpine3.12
    build: './compose/php74'
    networks:
      - mynet
    volumes:
      - ./src/project:/var/www/html/
    depends_on:
      - mysql

  mysql:
    build: './compose/mysql'
    ports:
      - "3306:3306"
    volumes:
      - ./src/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    build: './compose/phpmyadmin'
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  apache:
    image: httpd:2.4-alpine
    build: './compose/apache'
    depends_on:
      - php
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - ./src/project:/var/www/html/
      - ./compose/apache/:/usr/local/apache2/conf.d
networks:
  mynet: