# version: "3"
services:
  php74:
    build: './compose/php74'
    container_name: lamp_php74
    volumes:
      - ./src/project:/var/www/html/
    depends_on:
      - mysql
    networks:
      - mynet

  php70:
    build: './compose/php70'
    container_name: lamp_php70
    volumes:
      - ./src/project:/var/www/html/
    networks:
      - mynet

  mysql:
    build: './compose/mysql'
    container_name: lamp_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./src/data:/var/lib/mysql
      - ./src/sql:/root/sql/
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - mynet

  phpmyadmin:
    build: './compose/phpmyadmin'
    container_name: lamp_pma
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - mynet

  apache:
    #image: httpd:2.4-alpine
    build:
      context: './compose/apache'
      args:
        - HTTPD_ADMIN=${HTTPD_ADMIN}
    container_name: lamp_apache
    depends_on:
      - php74
      - php70
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - ./src/project:/var/www/html/
      - ./compose/apache/conf.d/:/usr/local/apache2/conf.d
      - ./src/logs/apache2:/usr/local/apache2/logs
 
      
networks:
  mynet: